My Library JS Project
SmithVyne/JS-Library-Project pull request #2
Opened 2020-09-16 17:36 UTC by SmithVyne

We created a simple Javascript application where users can:

1. Add new books they know to the library with a form.
2. Select whether or not they have read the books.
3. Update the statuses of the books later if they read them.
4. Delete books from the Library.

2020-09-16 19:35 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Good job so far :muscle: However, you need to implement the following requirements before this project can be approved.

- **_There should a package.json(I am not talking about the package-lock.json) file in your project which should contain all the dependencies_**

### OPTIONAL
* [ ] The form used to create a book should have validations, you should not be able to create an empty book
* [ ] It has data persistence by saving, retrieving, and updating the library books using [the localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))

#### _Reviewed by Temitayo Adeleke._

2020-09-16 19:35 UTC, lekegitrepo commented on README.md
> +* Open `index.html` in the browser and interact with the application.
- **_The readme should contain information about installing the dependencies._**

2020-09-16 19:35 UTC, lekegitrepo commented on script.js
> +};
- **_The Display Book should have a `render` function ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/render_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))_**

2020-09-16 23:03 UTC, uryelah requested changes
Hi **SmithVyne Nkereuwem & Alfred Ezaka**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with this project, it works quite well. There are some issues with the code organization and the linting but the nailed the main functionality of it!

Rock on! 🎸 👨‍🎤 

# Required Changes 🏗️ 🐛 💡

- [x] Please fix the eslint errors you are getting in the PR checks.
![Screenshot_2020-09-16 My Library JS Project by SmithVyne · Pull Request #2 · SmithVyne JS-Library-Project](https://user-images.githubusercontent.com/16193212/93399660-6691e480-f854-11ea-8eb8-9e559878c48a.png)

- [x] [OPTIONAL] You can add data persistence by saving, retrieving, and updating the library books using [the localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API).  ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))
That way the books you add will still be there even after you refresh the page.

(Check the comments below for the other fixes)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-17 09:06 UTC, rOluochKe requested changes
Hello @SmithVyne and @codecell 
### You have done well so far :clap: However, a few more issues are required for you to fix:-
- [ ] Host the app online and share the link on the readme file
- [ ] Your linting is producing error, kindly fi this. See the picture below
![lint](https://user-images.githubusercontent.com/8114528/93450014-1f503600-f8de-11ea-853d-3da148f40792.png)
- [ ] Separate app logic from dom manipulation
### Make these changes and submit for another code review. Good luck.
- Happy hacking!

By Raymond
Slack @iamraymond

2020-09-17 09:08 UTC, rOluochKe commented on script.js
> +};
### Separate app dom manipulation from app logic

2020-09-17 09:08 UTC, rOluochKe commented on script.js
> +    const box = document.querySelector('#check-book');
### Separate app dom manipulation from app logic

2020-09-17 09:08 UTC, SmithVyne commented
Hello @rOluochKe , hosting the app online is not part of the requirements

2020-09-17 09:36 UTC, SmithVyne commented on script.js
> +const hasRead = (book, i) => {
This would cause lint errors because the functions would be used before they were declared

2020-09-17 09:40 UTC, SmithVyne commented on script.js
> +};
This is a loop, and the best way to implement this section. Any other would be using more lines of code to do what we can in less

2020-09-17 12:59 UTC, sumancrest0001 commented
**Status: required changes :gear:
Hello TEAM,** You have done a nice job so far and make the website working as expected. But there are a couple of things that need to be improved. As mentioned by @uryelah  and @rOluochKe, we need to separate the logical part from the DOM part. It will make the code cleaner and file manageable. Let's not forget that we have to implement ES6 whenever it is applicable.

2020-09-17 13:01 UTC, sumancrest0001 commented on script.js
> +  };
[required] It seems that you haven't used this function. If not, please remove it.

2020-09-17 13:01 UTC, sumancrest0001 commented on script.js
> +const hasRead = (book, i) => {
Yes you are right.

2020-09-17 13:03 UTC, sumancrest0001 commented on script.js
> +  const newBook = new Book(title.value, author.value, pages.value, read);
[Required] Let's create a separate function to get values from input fields and return then and use those values to create a new book.

2020-09-17 13:05 UTC, sumancrest0001 commented on script.js
> +function Book(title, author, pages, read) {
[Required] Let's use ES6.

2020-09-17 13:08 UTC, sumancrest0001 commented on script.js
> +
[Required] You do not need parentheses for a single argument.
[Optional] You can use something meaningful instead of i.

2020-09-17 13:09 UTC, sumancrest0001 requested changes
**Kindly make the requested changes and submit the project for another review.
If you have any questions, Dm me on Slack (Suman Shrestha).
Happy coding !!!**

2020-09-17 14:54 UTC, SmithVyne commented on script.js
> +  };
The info method is part of the instructions for the Book constructor class

2020-09-17 15:14 UTC, SmithVyne commented on script.js
> +};
I'm afraid that is an old requirement for this project [Odin](https://www.theodinproject.com/courses/javascript/lessons/library)

2020-09-17 15:25 UTC, SmithVyne commented on script.js
> +};
This is outdated requirement for this project [Odin link](https://www.theodinproject.com/courses/javascript/lessons/library)

2020-09-17 15:40 UTC, SmithVyne commented on script.js
> +function Book(title, author, pages, read) {
Okay

2020-09-17 15:43 UTC, SmithVyne commented on script.js
> +  const newBook = new Book(title.value, author.value, pages.value, read);
That's possible, @sumancrest0001, but I do not think it is worth the extra lines of code.

2020-09-17 18:51 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @SmithVyne  @codecell nice job working on this team, this looks really good to me, everything works fine, kudos for making changes. **This is approved** 

Please merge and move on :slightly_smiling_face: 

**Raphael Noriode** :mask: STAY_SAFE

2020-09-17 19:21 UTC, merged